server:
  port: 8082

spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 5
          max-interval: 10s
          multiplier: 2

javainuse:
  rabbitmq:
    exchange: javainuse.exchange
    queue: javainuse.queue
    routingkey: javainuse.routingkey
    uri: amqps://b-a7ee691c-683a-40bf-9800-4cce4335d404.mq.us-east-1.amazonaws.com:5671
    username: pvanluom
    password: XtQBX8C6q^px1
    virtual-host: /